package himedia.portfoliospring.domain;

import lombok.Getter;
import lombok.Setter;
/*
 * [H2] 테이블
 

create table board
(
number bigint generated by default as identity,
title varchar(255),
content  varchar(255),
primary key (number)
);


 */

@Setter @Getter
public class Board {
	private Long number;
	private String title;
	private String content;
	private String writer;
}
